The `mean sqaure error` allow gradient descent to converge in a better way as compared to `mean absolute Error`

y = f(x) --> predictin function

`y = w1*x1 + w2*x2 + b`

    - start w1 and w2 with some random weights lets say 1
    - lets take bias as 0

## 1. Mean Absolute Error
    - taking the weights and bias above u calculate the predicted o/p
    - Take the difference of the result y_predicted and y_actual
    - Sum of all the errors for all data points
    - Take the mean

1. Mean Absolute Error is called the `Cost Function`
2. Each individual Loss is call `Loss Function`

Single round of all data points - termed as forward pass is called `1 epoch`

e1 = (y_actaul-y_predicted)<br>
e2 = (y_actaul-y_predicted)

MAE = (e1 + e2 + ---)/len(data)

In [9]:
import numpy as np
import math

In [3]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.3,0.7,1,0,0.5])

### Define the loss function - Mean Absolute Error - using PYTHON

In [20]:
## Using Python

def mae(y_true, y_predicted):
    total_error = 0
    for yt,yp in zip(y_true, y_predicted):
        total_error += abs(yt-yp)
    print('total error - ', total_error)
    mae = total_error/len(y_true)
    print('mae - ', mae)
    return mae

In [21]:
mae(y_true,y_predicted)

total error -  2.5
mae -  0.5


0.5

### Defining Mean Absolute Error using NUMPY

In [18]:
def np_mae(y_true,y_predicted):
    mae = np.mean(np.abs(y_true-y_predicted))
    print('mae - ', mae)
    return mae

In [19]:
np_mae(y_true,y_predicted)

mae -  0.5


0.5

## 2. MEAN SQAURED ERROR

In [53]:
# Using python

def mse(y_true, y_predicted):
    total_sq_error = 0
    
    for yt,yp in zip(y_true, y_predicted): 
        error = yt - yp
        error_sq = error**2
        total_sq_error += error_sq
    print('total_sq_error - ', total_sq_error)
    mse = total_sq_error/len(y_true)
    print('mse - ', mse)
    return mse

In [47]:
mse(y_true, y_predicted)

total_sq_error -  1.83
mse -  0.366


0.366

In [51]:
## using numpy

def np_mse(y_true, y_predicted):
    value = np.mean((y_true-y_predicted)**2)
    print('mse - ', value)
    return value
    

In [52]:
np_mse(y_true, y_predicted)

mse -  0.366


0.366

## 3. LogLoss/ BinaryCrossEntropy

In [22]:
np.log(0) # if we take the log of 0 its infinite

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_3944\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

  - if we take the log of 0 its infinite
  - We need to convert the 0 values veru close to 0
  - Also for the value 1-y_predicted, we need to handle the value 1
  - Need to introduce `Epsilon`

In [23]:
epsilon = 1e-15

In [25]:
y_predicted

array([1, 1, 0, 0, 1])

In [27]:
np.log(y_predicted)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_3944\815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [31]:
## Handling the values 0, log(0) is infinite


y_predicted_new = [max(i,epsilon) for i in y_predicted] 
## if i=0 to avoid the infinite value , we took the max value between 0 and 1e-15, so that log(i) is not infinite

y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [32]:
## Handling the values 1, log(1-1) is infinite

y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new] 
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [34]:
np.log(y_predicted)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_3944\815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [33]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

### logloss = - (y_true*log(y_predicted)  + (1-y_true)* log(1-y_predicted) )/ len(array)

In [40]:
y_predicted_new = np.array(y_predicted_new)

In [41]:
1-y_predicted_new

array([9.99200722e-16, 9.99200722e-16, 1.00000000e+00, 1.00000000e+00,
       9.99200722e-16])

In [43]:
-(np.mean(y_true*np.log(y_predicted_new)  + (1-y_true)*np.log(1-y_predicted_new)))

17.2696280766844

### Creating a function

In [44]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    loss_value = -(np.mean(y_true*np.log(y_predicted_new)  + (1-y_true)*np.log(1-y_predicted_new)))
    return loss_value

In [45]:
log_loss(y_true, y_predicted)

17.2696280766844