In [1]:
import numpy as np

# 1-D numpy array

In [2]:
# 1. Creating array from list
np_arr1 = np.array([1,4,7,9])
np_arr1

array([1, 4, 7, 9])

In [3]:
# 2. Creating array from range
np_arr2 = np.array(range(5))
np_arr2

array([0, 1, 2, 3, 4])

In [4]:
# 3. using arange
np_arr3 = np.arange(1,10,2)
np_arr3

array([1, 3, 5, 7, 9])

# 2-D numpy Array

In [5]:
arr1 = np.array([1,2,3,4,5,6]).reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr3 = np.arange(6).reshape(3,2)
arr3

array([[0, 1],
       [2, 3],
       [4, 5]])

In [9]:
arr4 = np.empty((3,4), dtype=int)
arr4

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
arr5 = np.full((3,5), '-')
arr5

array([['-', '-', '-', '-', '-'],
       ['-', '-', '-', '-', '-'],
       ['-', '-', '-', '-', '-']], dtype='<U1')

In [12]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         ``np.array(fill_value).dtype``.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that pas