# Numpy vs List

In [1]:
heights = [43, 67, 71, 63, 98]
heights

[43, 67, 71, 63, 98]

In [2]:
# conver heightin inches to cm
heights * 2.54 # ERROR

TypeError: can't multiply sequence by non-int of type 'float'

In [3]:
import numpy as np

In [5]:
## declaring np array
npHeights = np.array([43, 67, 71, 63, 98])
npHeights

array([43, 67, 71, 63, 98])

In [6]:
type(npHeights)

numpy.ndarray

In [8]:
npHeights* 2.54

array([109.22, 170.18, 180.34, 160.02, 248.92])

# Numpy methods

In [10]:
list_1 = [1, 2, 3]
list_2 = [4, 5, 6]
list_1 + list_2

[1, 2, 3, 4, 5, 6]

In [13]:
np1 = np.array([1, 2, 3])
np2 = np.array([4, 5, 6])
np1 + np2

array([5, 7, 9])

In [14]:
npHeights

array([43, 67, 71, 63, 98])

# N-D array

In [15]:
type(npHeights)

numpy.ndarray

In [16]:
# ndarray -> n dimentional array

# Quiz

In [18]:
## Select the correct option to create a 1-d array using the following elements (1.0, 2, 3.5, 0.2, True). 
## (Note that ‘True’ must be provided as a Boolean value, not as a string.)

np.array( [1.0, 2, 3.5, 0.2, True] ) # datatype is float

array([1. , 2. , 3.5, 0.2, 1. ])

## Creating array from tuple

In [19]:
tup = (2,4,7,6)
np.array((2,4,7,6)) # [2, 4, 7, 6]

array([2, 4, 7, 6])

# Case Study - Cricket tournament

In [20]:
heights = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 72, 75, 74, 74, 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76, 70, 72, 80, 74, 74, 71, 70, 72, 71, 74, 71, 72, 71, 74, 69, 76, 75, 75, 76, 73, 76, 73, 77, 73, 72, 72, 77, 77, 71, 74, 74, 73, 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 76, 73, 74, 75, 75, 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75, 73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72, 72, 74, 73, 74, 76, 75, 80, 72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75, 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 73, 73, 73, 72, 72, 72, 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 74, 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74, 70, 77, 73, 72, 76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72, 75, 75, 70, 72, 70, 74, 71, 76, 73, 76, 71, 69, 72, 72, 69, 73, 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 71, 72, 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76, 73, 73, 73, 75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74, 74, 73, 75, 76, 73, 77, 72, 73, 77, 76, 71, 75, 73, 74, 77, 71, 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 73, 74, 77, 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71, 74, 70, 79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74, 74, 70, 73, 73, 74, 77, 72, 76, 73, 73, 72, 74, 74, 71, 72, 75, 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 79, 76, 73, 76, 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71, 71, 72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75, 79, 72, 77, 73, 75, 75, 75, 73, 73, 76, 77, 75, 70, 71, 71, 75, 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 75, 74, 69, 73, 72, 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70, 75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73, 79, 71, 72, 74, 74, 74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77, 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 72, 71, 71, 71, 72, 72, 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 75, 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70, 75, 71, 76, 73, 68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76, 72, 72, 74, 76, 73, 76, 75, 70, 71, 74, 72, 73, 76, 76, 73, 71, 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 76, 74, 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72, 72, 73, 72, 74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75, 75, 76, 74, 74, 73, 74, 71, 74, 75, 76, 74, 76, 76, 73, 75, 75, 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 71, 82, 72, 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73, 76, 75, 70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72, 77, 74, 75, 75, 75, 75, 72, 74, 71, 76, 71, 75, 76, 83, 75, 74, 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 74, 72, 71, 70, 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75, 77, 76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70, 70, 74, 75, 74, 74, 73, 74, 75, 77, 73, 74, 76, 74, 75, 73, 76, 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 73, 67, 67, 76, 74, 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75, 72, 75, 73, 74, 75, 75, 73]

In [23]:
import numpy as np
heights_in = np.array(heights)
heights_in

array([74, 74, 72, ..., 75, 75, 73])

In [24]:
#### length of np array
len(heights_in)

1015

In [25]:
heights_in.size

1015

In [26]:
heights_in.shape

(1015,)

## converts heights from inches to meters

In [28]:
heights_m = heights_in * 0.0254
heights_m

array([1.8796, 1.8796, 1.8288, ..., 1.905 , 1.905 , 1.8542])

# Sub-Setting Array

## Fetch the first element from the array

In [29]:
heights_in[0]

74

In [30]:
heights_in[-1]

73

In [31]:
heights_in[:5]

array([74, 74, 72, 72, 73])

In [32]:
heights_in[0:5]

array([74, 74, 72, 72, 73])

In [33]:
heights_in[-5:]

array([73, 74, 75, 75, 73])

# Conditional Sub-Setting Arrays

In [35]:
heights_in < 73

array([False, False,  True, ..., False, False, False])

In [40]:
heights_in[heights_in < 73]

array([72, 72, 69, 69, 71, 71, 69, 70, 72, 71, 69, 71, 70, 72, 70, 72, 72,
       70, 70, 70, 68, 71, 72, 68, 71, 72, 72, 69, 72, 72, 72, 72, 71, 70,
       72, 71, 72, 71, 72, 72, 72, 70, 71, 70, 71, 71, 72, 71, 72, 71, 72,
       71, 71, 72, 72, 72, 71, 70, 71, 69, 71, 72, 72, 70, 72, 71, 72, 71,
       72, 72, 72, 71, 70, 72, 71, 70, 72, 71, 71, 72, 71, 69, 72, 72, 71,
       70, 72, 72, 72, 70, 71, 72, 71, 72, 69, 72, 70, 70, 72, 72, 72, 71,
       72, 72, 72, 72, 72, 72, 71, 72, 70, 71, 71, 72, 70, 72, 71, 72, 70,
       72, 70, 71, 71, 69, 72, 72, 69, 69, 72, 71, 72, 72, 71, 72, 71, 71,
       72, 72, 72, 70, 72, 71, 71, 72, 71, 71, 72, 69, 70, 71, 70, 72, 72,
       70, 72, 72, 70, 72, 72, 71, 72, 70, 71, 71, 72, 72, 72, 71, 70, 71,
       71, 72, 72, 69, 71, 70, 72, 70, 71, 71, 69, 70, 72, 72, 72, 72, 69,
       72, 72, 71, 70, 70, 69, 71, 72, 72, 70, 70, 72, 71, 72, 72, 72, 72,
       71, 72, 72, 70, 72, 71, 71, 70, 72, 71, 71, 71, 72, 72, 71, 72, 72,
       71, 72, 72, 72, 72

In [51]:
underHeightPlayers = heights_in[heights_in < 73]
underHeightPlayers

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [43]:
underHeightPlayers.size

318

## Largest Value

In [46]:
underHeightPlayers.max()

72

## Lowest value

In [47]:
underHeightPlayers.min()

67

In [48]:
underHeightPlayers.mean()

71.1006289308176

## QUIZ

In [49]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[ : : -2]) # [2, 5, 7, 4, 3, 1]

[2, 5, 7, 4, 3, 1]


In [52]:
## How would you extract all the elements with an odd index in a given array?
## (Hint: Odd index refers to the position of the element, not the actual value)

array[1: : 2]


NameError: name 'array' is not defined

In [ ]:
## From a given array, extract all the elements which are greater than 'm' and less than 'n'. 
## Note: 'm' and 'n' are integer values provided as input.

import numpy as np
array_1 = np.array(input_list)#start writing your code from here
final_array = array_1[(array_1 > m) & (array_1<n)]

print(final_array)