In [4]:
class Arithmatic:
    
    def __init__(self,num1,num2):
        self.num1 = num1
        self.num2 = num2
        
    def addition(self):
        return self.num1 + self.num2
    
    def sub(self):
        return self.num1-self.num2
    
    def mul(self):
        return self.num1 * self.num2
    
a1 = Arithmatic(12,67)
print(a1.addition())
print(a1.sub())
print(a1.mul())

79
-55
804


In [5]:
import numpy as np

In [6]:
arr = [1,3,5,7,9]
np_arr = np.array(arr)
np_arr

array([1, 3, 5, 7, 9])

In [7]:
arr2 = np.array([[1,2], [3,4]])
arr2

array([[1, 2],
       [3, 4]])

In [8]:
arr3d = np.array([[[1,2], [3,4]], [[5,6], [7,8]] ])
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10,2, dtype="float")

array([1., 3., 5., 7., 9.])

# zeros and ones

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.zeros((4,2), dtype="int")

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [16]:
np.zeros((4,2), dtype="int").reshape(2,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.diag([6,3])

array([[6, 0],
       [0, 3]])

In [25]:
np.diag(np.full(4,1))

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [33]:
np_arr.shape[-1]

5

In [35]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [37]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
a.reshape((-1,a.shape[0]))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
a.reshape((-1,1)) # -1 indicates the shape[-1]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [48]:
a.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [53]:
n = np.array([1,3,5])
n[1:-1]

array([3])

In [57]:
a = np.array([1,2,3])
b = np.array([2,2,(2,4)])
a*b

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_50624\2035960674.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b = np.array([2,2,(2,4)])


array([2, 4, (2, 4, 2, 4, 2, 4)], dtype=object)

# broadcasting
- dimension should match or dimension should be 1

In [55]:
a = np.array([1,2,3])
b = 2
a*b

array([2, 4, 6])

# concat

In [59]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
arr = np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 1, 2, 3])

In [63]:
arr = np.arange(1,11)
new = np.array_split(arr,3)
new

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [64]:
np.where(arr%3==0) # position

(array([2, 5, 8], dtype=int64),)

# PANDAS

In [65]:
import pandas as pd

In [66]:
d = {'col1':[1,2], 'col2':[3,4]}
df = pd.DataFrame(d)
df

col1  col2
0     1     3
1     2     4

In [67]:
df2 = pd.DataFrame(np.array([[1,2,3], [4,5,6], [7,8,9]]), columns=['a','b','c'])
df2

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
## https://www.dropbox.com/scl/fo/c5khpmslfkc5g6vd9tadb/h?dl=0&rlkey=wjwcjoyguokkzs19qzt14xoz4

In [71]:
a = np.array([2,3,4]) 
print(a[a%2==0]) # it return the values at the positions
print(np.where(a%2==0)) # it returs the position

[2 4]
(array([0, 2], dtype=int64),)


In [73]:
df = pd.read_csv('https://raw.githubusercontent.com/scpike/us-state-county-zip/master/geo-data.csv')
df.head()

URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>