In [58]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [59]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [60]:
med_value = df.bedrooms.median()

In [61]:
df.bedrooms.fillna(med_value, inplace=True)

In [62]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [63]:
from sklearn import linear_model

reg = linear_model.LinearRegression()
reg.fit(df.drop('price', axis=1), df.price)

LinearRegression()

In [64]:
reg.intercept_

221323.0018654043

In [65]:
reg.predict([[3000, 3, 40]])

C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

# Excercise

In exercise folder (same level as this notebook on github) there is **hiring.csv**. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,


**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**


## Answer:

53713.86 and 93747.79

In [66]:
hiring_df = pd.read_csv('hiring.csv')
hiring_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

### filling zero for experience having NaN

In [67]:
hiring_df.experience.fillna('zero', inplace=True)
hiring_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

### filling mean value for test_scores having NaN values

In [68]:
import math

mean_value = math.floor(hiring_df['test_score(out of 10)'].mean())
mean_value

7

In [69]:
hiring_df['test_score(out of 10)'].fillna(mean_value, inplace=True)
hiring_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [70]:
!pip install word2number


[notice] A new release of pip available: 22.3 -> 23.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [71]:
from word2number import w2n

In [72]:
hiring_df['experience'] = hiring_df['experience'].apply(lambda x : w2n.word_to_num(x))

In [73]:
hiring_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [74]:
X_train = hiring_df.drop('salary($)', axis=1)

In [75]:
X_train

experience  test_score(out of 10)  interview_score(out of 10)
0           0                    8.0                           9
1           0                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6
5           3                    7.0                          10
6          10                    7.0                           7
7          11                    7.0                           8

In [76]:
y_train = hiring_df['salary($)']

In [77]:
y_train

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [78]:
### Create model

lr = linear_model.LinearRegression()
lr.fit(X=X_train, y=y_train)

LinearRegression()

In [79]:
lr.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [80]:
lr.intercept_

14992.65144669314

In [81]:
lr.predict([[2,9,6]])

C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [82]:
lr.predict([[12,10,10]])

C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])